# Generated by Django 6.0.2 on 2026-03-12 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0002_favorito_listausuario_sugestaoitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorito',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'item')},
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(default='perfis/default.png', upload_to='perfis')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
