# Generated by Django 6.0.2 on 2026-03-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0003_alter_favorito_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='itens/'),
        ),
    ]
