# Generated by Django 6.0.2 on 2026-03-13 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0004_item_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categoria',
        ),
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.ManyToManyField(blank=True, related_name='itens', to='acervo.categoria'),
        ),
    ]
