# Generated by Django 6.0.2 on 2026-03-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0005_remove_item_categoria_item_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
