# Generated by Django 6.0.2 on 2026-03-01 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(blank=True, default='Anônimo', max_length=200)),
                ('ano', models.IntegerField()),
                ('tipo', models.CharField(choices=[('livro', 'Livro'), ('revista', 'Revista'), ('manuscrito', 'Manuscrito'), ('artigo', 'Artigo'), ('outro', 'Outro')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='acervo.categoria')),
            ],
            options={
                'verbose_name_plural': 'Itens',
                'ordering': ['-criado_em'],
            },
        ),
    ]
